server:
  port: 8111

db:
  type: 'mariadb'
  host: 'mariadb'
  port: 3306
  database: 'chaosarchives'
  username: 'mariadb'
  password: 'mariadb'
  synchronize: false

redis:
  host: 'redis'
  port: 6379

auth:
  jwtSecret: 'secret'
  jwtExpiry: '30d'
