server:
  port: 8111
  frontendRoot: 'http://localhost:8080'
  maxUploadSpacePerUserMiB: 200
  stewardWebhookPort: 8112
  stewardWebhookUrl: 'http://steward:8112'

db:
  type: 'mariadb'
  host: 'mariadb'
  port: 3306
  database: 'chaosarchives'
  username: 'mariadb'
  password: 'mariadb'
  synchronize: false

redis:
  host: 'redis'
  port: 6379

mail:
  host: 'smtp.example.com'
  port: 25
  secure: true
  username: 'user'
  password: 'password'
  from: 'Chaos Archives <chaosarchives@localhost>'

auth:
  jwtSecret: 'secret'
  jwtExpiry: '30d'

s3:
  endpoint: 'https://servername.tld'
  bucketName: 'mybucket'
  publicRootUrl: 'https://publicservername.tld'
  accessKeyId: 'MY_ACCESS_KEY'
  secretAccessKey: 'MY_SECRET_ACCESS_KEY'

discord:
  botToken: 'INSERT_TOKEN_HERE'
  serverId: 'INSERT_ID_HERE'
  announcementChannel: 'INSERT_ID_HERE'
  noticeboardChannel: 'INSERT_ID_HERE'
