server:
  port: 8111

db:
  type: 'postgres'
  host: 'postgres'
  port: 5432
  database: 'chaosarchives'
  username: 'postgres'
  password: 'postgres'
  synchronize: false

redis:
  host: 'redis'
  port: 6379

auth:
  jwtSecret: 'secret'
  jwtExpiry: '30d'
