version: '3.1'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./volumes/postgres:/var/lib/postgresql:rw,z
    expose:
      - 5432
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_EXTERNAL_PORT=15432
      - POSTGRES_DB=uno
