version: '3.7'

services:
  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - ./volumes/redis:/data:rw,z
    ports:
      - '16379:6379'
    expose:
      - 6379

  mariadb:
    image: mariadb:10.6
    restart: always
    volumes:
      - ./volumes/mariadb:/var/lib/mysql:rw,z
    expose:
      - 3306
    ports:
      - '13306:3306'
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_USER=mariadb
      - MARIADB_PASSWORD=mariadb
      - MARIADB_DATABASE=chaosarchives
      - TZ=UTC

  chaosarchives:
    build: ./
    image: chaosarchives
    restart: always
    init: true
    links:
      - mariadb
      - redis
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - '${CHAOSARCHIVES_EXTERNAL_PORT:-8111}:8111'
