name: Deploy Client
run-name: Released latest version of client to VM.
on:
  workflow_dispatch:
  push:
    branches:
      - 'releases/**'
jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Quasar
        # You may pin to the exact commit or the version.
        # uses: joshstrange/setup-quasar@35f247113004c44d5ce8a3e9a4133b78f9383404
        uses: joshstrange/setup-quasar@1.0.0
        with:
          quasar-version: 1.3.2
      - name: Build
        run: |
          cd client |
          quasar build
